### ISSUE TITLE
Can't find module 'amazon-associate'

### ISSUE THREAD

**Issue by saitheexplorer** [snd/amazon-associate#2]
Installed the module with `npm install amazon-associate` but when I try to require it, I'm  getting an error with the require.

`var Amazon = require('amazon-associate');` is causing the error

```
Error: Cannot find module 'amazon-associate'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by snd** [comment]
the npm module of `amazon-associate` only contains the coffeescript sources and not the compiled javascript.

a temporary workaround is to add `"coffee-script": "1.6.3"` to the dependencies section in your `package.json`,
run `npm install` and call `require('coffee-script');` somewhere before `var Amazon = require('amazon-associate');`.
`require('coffee-script');` enables the loading of "coffeescript only modules" from javascript.

i will update `amazon-associate` in the coming days such that the workaround is no longer needed.

**Comment by snd** [comment]
use the new version `0.3.0`. it contains the compiled javascript and can be required without the workaround.

**Comment by MathRobin** [comment]
Bug continues to exist with 0.3.1. Had to get back to 0.3.0
